# Generated by Django 6.0.5 on 2026-05-11 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='name (EN)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='name (AR)')),
                ('description_en', models.TextField(verbose_name='description (EN)')),
                ('description_ar', models.TextField(verbose_name='description (AR)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='name (EN)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='name (AR)')),
                ('description_en', models.TextField(verbose_name='description (EN)')),
                ('description_ar', models.TextField(verbose_name='description (AR)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('farm_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='farm cost')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='selling price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='low stock threshold')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sort_order'],
            },
        ),
    ]
