# Generated by Django 6.0.5 on 2026-05-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False, verbose_name='organic'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, default='kg', max_length=10, verbose_name='weight unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='weight value'),
        ),
    ]
