# Generated by Django 6.0.5 on 2026-06-04 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='previous status')),
                ('new_status', models.CharField(max_length=20, verbose_name='new status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='changed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order status history',
                'verbose_name_plural': 'order status histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
