# Generated by Django 6.0.6 on 2026-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_label',
            field=models.CharField(blank=True, help_text="e.g. 'Home', 'Work', or a custom label — denormalized at checkout.", max_length=50, verbose_name='delivery address label'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude captured at checkout time (e.g. 31.963158).', max_digits=9, null=True, verbose_name='shipping latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude captured at checkout time (e.g. 35.930359).', max_digits=9, null=True, verbose_name='shipping longitude'),
        ),
    ]
