# Generated by Django 6.0.6 on 2026-07-04 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10, verbose_name='label')),
                ('custom_label', models.CharField(blank=True, help_text="Display name when label is 'Other', e.g. 'Mom's House'.", max_length=50, verbose_name='custom label')),
                ('full_address', models.TextField(help_text='Human-readable address text, e.g. from map reverse-geocoding.', verbose_name='full address')),
                ('extra_details', models.CharField(blank=True, help_text='Building / floor / apartment number, landmark, etc.', max_length=255, verbose_name='extra details')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude coordinate (e.g. 31.963158)', max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude coordinate (e.g. 35.930359)', max_digits=9, verbose_name='longitude')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='default address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
