import { createContext, useContext, useEffect, useState } from 'react';

// ─── Translation strings ──────────────────────────────────────────────────────
const translations = {
  en: {
    appName: 'Mawasem',
    searchPlaceholder: 'Search products…',
    cart: 'Cart',
    home: 'Home',
    categories: 'Categories',
    farmers: 'Farmers',
    login: 'Login',
    logout: 'Logout',
    loading: 'Loading…',
    noProducts: 'No products found.',
    allCategories: 'All Categories',
    sortBy: 'Sort by',
    priceAsc: 'Price: Low → High',
    priceDesc: 'Price: High → Low',
    stock: 'Stock',
    outOfStock: 'Out of stock',
    addToCart: 'Add to cart',
    viewDetails: 'View details',
    verified: 'Verified',
    // Cart page
    emptyCart: 'Your cart is empty',
    emptyCartSub: 'Discover fresh products from local farmers.',
    browseProducts: 'Browse Products',
    orderSummary: 'Order Summary',
    item: 'item',
    items: 'items',
    shippingAddress: 'Shipping Address',
    placeOrder: 'Place Order',
    placingOrder: 'Placing order…',
    clearCart: 'Clear cart',
    remove: 'Remove item',
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
    orderPlaced: 'Order Placed!',
    orderNumber: 'Order #',
    orderTotal: 'Total',
    continueShopping: 'Continue Shopping',
    checkoutError: 'Checkout failed. Please try again.',
    cartLoadError: 'Failed to load your cart. Please refresh.',
    // Product detail
    backToProducts: 'Back to Products',
    quantity: 'Quantity',
    inStock: 'In stock',
    soldBy: 'Sold by',
    // Sign up
    signup: 'Sign Up',
    // Farmer dashboard
    myFarm: 'My Farm',
    updateStock: 'Update Stock',
    farmerDashboard: 'Farm Dashboard',
    addNewCrop: 'Add New Crop',
    myProducts: 'My Crops',
    cropName: 'Name',
    incomingOrders: 'Incoming Orders',
    activeProducts: 'Active Products',
    outOfStockItems: 'Out of Stock',
    pendingOrders: 'Pending Orders',
    stockLevel: 'Stock',
    pricePerUnit: 'Price / unit',
    orderStatus: 'Status',
    orderDate: 'Order Date',
    customer: 'Customer',
    phone: 'Phone',
    farmCost: 'Farm Cost',
    nameEn: 'Name (English)',
    nameAr: 'Name (Arabic)',
    descriptionEn: 'Description (EN)',
    descriptionAr: 'Description (AR)',
    sellingPrice: 'Selling Price',
    discountPrice: 'Discount Price',
    selectCategory: 'Category',
    organic: 'Organic product',
    uploadImage: 'Product image',
    addCrop: 'Add Crop',
    cancel: 'Cancel',
    save: 'Save',
    changeStatus: 'Move to…',
    status_pending: 'Pending',
    status_processing: 'Processing',
    status_shipped: 'Shipped',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    noProducts: 'No crops yet. Add your first!',
    noOrders: 'No incoming orders yet.',
    genericError: 'Something went wrong. Please try again.',
    loadingDashboard: 'Loading dashboard…',
    notAFarmer: 'Farmer profile not found.',
    // Profile settings
    profileSettings: 'Profile Settings',
    profileTab: 'Profile',
    paymentTab: 'Payment',
    farmNameLabel: 'Farm Name',
    selectCity: 'Select city…',
    farmBio: 'About your farm',
    phoneLabel: 'Phone Number',
    savingProfile: 'Saving…',
    profileSaved: 'Changes saved!',
    // Financial metrics
    totalSales: 'Total Sales',
    grossRevenue: 'Gross Revenue',
    netProfit: 'Net Profit',
    netProfitSub: 'After 10% platform fee',
    // Payment settings
    paymentMethod: 'Receive Payments Via',
    bankTransfer: 'Local Bank Transfer',
    mobileWallet: 'Mobile Wallet',
    bankName: 'Bank Name',
    accountHolder: 'Account Holder',
    iban: 'IBAN',
    walletType: 'Wallet Provider',
    walletPhone: 'Wallet Phone',
    cliqAlias: 'CliQ Alias',
    paymentNote: 'Payment info is saved locally on your device.',
    savePayment: 'Save Payment Info',
    // Delivery management
    deliveryMethod: 'Delivery Method',
    selfDelivery: 'Self Delivery',
    partnerDelivery: 'Delivery Partner',
    courierName: 'Courier Name',
    trackingNum: 'Tracking Number',
    confirmShipped: 'Confirm Shipped',
    // Notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications yet',
    markAllRead: 'Mark all as read',
    // Orders page
    myOrders: 'My Orders',
    orderHistory: 'Order History',
    noOrdersYet: "You haven't placed any orders yet.",
    orderPreview: 'Order Preview',
    deliveryAddress: 'Delivery Address',
    statusHistory: 'Status History',
    // Address book & map
    addressBook: 'My Addresses',
    addAddress: 'Add Address',
    editAddress: 'Edit',
    deleteAddress: 'Delete',
    setAsDefault: 'Set as default',
    defaultAddress: 'Default',
    addressLabel_home: 'Home',
    addressLabel_work: 'Work',
    addressLabel_other: 'Other',
    noAddressesYet: "You haven't saved any addresses yet.",
    addFirstAddress: 'Add your first address',
    addressLabelField: 'Label',
    customLabel: 'Custom name',
    customLabelPlaceholder: "e.g. Mom's House",
    customLabelRequired: 'Please give this address a name.',
    extraDetails: 'Building / floor / apartment (optional)',
    extraDetailsPlaceholder: 'e.g. Building 4, 2nd floor',
    pinLocationRequired: 'Please pick a location on the map.',
    searchAddressPlaceholder: 'Search for an address…',
    useMyLocation: 'Use my current location',
    locatingYou: 'Locating…',
    confirmLocation: 'Confirm location',
    selectDeliveryAddress: 'Delivery Address',
    addNewAddressOption: 'Add a new address',
    editOnMap: 'Edit on map',
    saveAddressForLater: 'Save this address for later',
    openInMaps: 'Open in Maps',
    deliveryLocation: 'Delivery Location',
  },
  ar: {
    appName: 'مواسم',
    searchPlaceholder: 'ابحث عن المنتجات…',
    cart: 'السلة',
    home: 'الرئيسية',
    categories: 'الفئات',
    farmers: 'المزارعون',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    loading: 'جاري التحميل…',
    noProducts: 'لا توجد منتجات.',
    allCategories: 'جميع الفئات',
    sortBy: 'ترتيب حسب',
    priceAsc: 'السعر: من الأقل',
    priceDesc: 'السعر: من الأعلى',
    stock: 'المخزون',
    outOfStock: 'نفد من المخزون',
    addToCart: 'أضف للسلة',
    viewDetails: 'عرض التفاصيل',
    verified: 'موثّق',
    // Cart page
    emptyCart: 'سلتك فارغة',
    emptyCartSub: 'اكتشف المنتجات الطازجة من المزارعين المحليين.',
    browseProducts: 'تصفح المنتجات',
    orderSummary: 'ملخص الطلب',
    item: 'عنصر',
    items: 'عناصر',
    shippingAddress: 'عنوان الشحن',
    placeOrder: 'تأكيد الطلب',
    placingOrder: 'جاري تأكيد الطلب…',
    clearCart: 'إفراغ السلة',
    remove: 'إزالة العنصر',
    decrease: 'تقليل الكمية',
    increase: 'زيادة الكمية',
    orderPlaced: '!تم تأكيد الطلبية',
    orderNumber: 'رقم الطلب',
    orderTotal: 'الإجمالي',
    continueShopping: 'مواصلة التسوق',
    checkoutError: 'فشل إتمام الطلب. يرجى المحاولة مرة أخرى.',
    cartLoadError: 'فشل تحميل السلة. يرجى تحديث الصفحة.',
    // Product detail
    backToProducts: 'العودة إلى المنتجات',
    quantity: 'الكمية',
    inStock: 'متاح',
    soldBy: 'من مزرعة',
    // Sign up
    signup: 'إنشاء حساب',
    // Farmer dashboard
    myFarm: 'مزرعتي',
    updateStock: 'تعديل المخزون',
    farmerDashboard: 'لوحة المزرعة',
    addNewCrop: 'إضافة محصول',
    myProducts: 'محاصيلي',
    cropName: 'الاسم',
    incomingOrders: 'الطلبات الواردة',
    activeProducts: 'المنتجات النشطة',
    outOfStockItems: 'نفد من المخزون',
    pendingOrders: 'الطلبات المعلقة',
    stockLevel: 'المخزون',
    pricePerUnit: 'السعر / وحدة',
    orderStatus: 'الحالة',
    orderDate: 'تاريخ الطلب',
    customer: 'العميل',
    phone: 'الهاتف',
    farmCost: 'تكلفة المزرعة',
    nameEn: 'الاسم (إنجليزي)',
    nameAr: 'الاسم (عربي)',
    descriptionEn: 'الوصف (EN)',
    descriptionAr: 'الوصف (AR)',
    sellingPrice: 'سعر البيع',
    discountPrice: 'سعر الخصم',
    selectCategory: 'الفئة',
    organic: 'منتج عضوي',
    uploadImage: 'صورة المنتج',
    addCrop: 'إضافة المحصول',
    cancel: 'إلغاء',
    save: 'حفظ',
    changeStatus: 'انتقل إلى…',
    status_pending: 'قيد الانتظار',
    status_processing: 'قيد المعالجة',
    status_shipped: 'تم الشحن',
    status_completed: 'مكتمل',
    status_cancelled: 'ملغي',
    noProducts: 'لا توجد محاصيل بعد. أضف أول محصول!',
    noOrders: 'لا توجد طلبات واردة بعد.',
    genericError: 'حدث خطأ ما. يرجى المحاولة مجدداً.',
    loadingDashboard: 'جاري تحميل اللوحة…',
    notAFarmer: 'لم يتم العثور على ملف المزارع.',
    // Profile settings
    profileSettings: 'إعدادات الملف الشخصي',
    profileTab: 'الملف الشخصي',
    paymentTab: 'الدفع',
    farmNameLabel: 'اسم المزرعة',
    selectCity: 'اختر مدينة…',
    farmBio: 'نبذة عن المزرعة',
    phoneLabel: 'رقم الهاتف',
    savingProfile: 'جاري الحفظ…',
    profileSaved: 'تم حفظ التغييرات!',
    // Financial metrics
    totalSales: 'إجمالي المبيعات',
    grossRevenue: 'إجمالي الإيرادات',
    netProfit: 'صافي الأرباح',
    netProfitSub: 'بعد خصم 10% رسوم المنصة',
    // Payment settings
    paymentMethod: 'طريقة استلام المدفوعات',
    bankTransfer: 'تحويل بنكي محلي',
    mobileWallet: 'محفظة إلكترونية',
    bankName: 'اسم البنك',
    accountHolder: 'اسم صاحب الحساب',
    iban: 'رقم IBAN',
    walletType: 'نوع المحفظة',
    walletPhone: 'رقم هاتف المحفظة',
    cliqAlias: 'اسم CliQ',
    paymentNote: 'بيانات الدفع محفوظة محلياً على جهازك.',
    savePayment: 'حفظ بيانات الدفع',
    // Delivery management
    deliveryMethod: 'طريقة التوصيل',
    selfDelivery: 'توصيل ذاتي',
    partnerDelivery: 'شركة توصيل',
    courierName: 'اسم المندوب',
    trackingNum: 'رقم التتبع',
    confirmShipped: 'تأكيد الشحن',
    // Notifications
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات بعد',
    markAllRead: 'تحديد الكل كمقروء',
    // Orders page
    myOrders: 'طلباتي',
    orderHistory: 'سجل الطلبات',
    noOrdersYet: 'لم تُقدِّم أي طلب حتى الآن.',
    orderPreview: 'معاينة الطلب',
    deliveryAddress: 'عنوان التوصيل',
    statusHistory: 'سجل الحالات',
    // Address book & map
    addressBook: 'عناويني',
    addAddress: 'إضافة عنوان',
    editAddress: 'تعديل',
    deleteAddress: 'حذف',
    setAsDefault: 'تعيين كافتراضي',
    defaultAddress: 'افتراضي',
    addressLabel_home: 'المنزل',
    addressLabel_work: 'العمل',
    addressLabel_other: 'آخر',
    noAddressesYet: 'لم تقم بحفظ أي عناوين بعد.',
    addFirstAddress: 'أضف أول عنوان لك',
    addressLabelField: 'التصنيف',
    customLabel: 'اسم مخصص',
    customLabelPlaceholder: 'مثال: منزل الوالدة',
    customLabelRequired: 'يرجى إعطاء هذا العنوان اسماً.',
    extraDetails: 'المبنى / الطابق / الشقة (اختياري)',
    extraDetailsPlaceholder: 'مثال: مبنى 4، الطابق الثاني',
    pinLocationRequired: 'يرجى تحديد الموقع على الخريطة.',
    searchAddressPlaceholder: 'ابحث عن عنوان…',
    useMyLocation: 'استخدام موقعي الحالي',
    locatingYou: 'جارٍ تحديد الموقع…',
    confirmLocation: 'تأكيد الموقع',
    selectDeliveryAddress: 'عنوان التوصيل',
    addNewAddressOption: 'إضافة عنوان جديد',
    editOnMap: 'تعديل على الخريطة',
    saveAddressForLater: 'حفظ هذا العنوان لاستخدامه لاحقاً',
    openInMaps: 'فتح في الخرائط',
    deliveryLocation: 'موقع التوصيل',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem('lang') ?? 'ar',
  );

  const isRTL = lang === 'ar';
  const dir = isRTL ? 'rtl' : 'ltr';
  const t = translations[lang];

  // Keep <html> dir + lang in sync so browser-level RTL is also applied.
  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    localStorage.setItem('lang', lang);
  }, [lang, dir]);

  const toggleLang = () => setLang((l) => (l === 'ar' ? 'en' : 'ar'));

  return (
    <LanguageContext.Provider value={{ lang, dir, isRTL, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside <LanguageProvider>');
  return ctx;
}
